"use client";
import { useState } from "react";
type Vestiging={id:string;naam:string}; type Dag={datum:string;uren:number;kosten:number;ontbrekendUurloon:number}; type Medewerker={medewerkerId:string;naam:string;uren:number;kosten:number;uurloon:number|null};
const euro=(n:number)=>new Intl.NumberFormat("nl-NL",{style:"currency",currency:"EUR"}).format(n);
const datum=(s:string)=>new Intl.DateTimeFormat("nl-NL",{weekday:"short",day:"2-digit",month:"2-digit"}).format(new Date(s+"T12:00:00"));
export default function LoonkostenRapport(p:{vestigingen:Vestiging[];vestigingId:string;jaar:number;weeknummer:number;weekBestaat:boolean;weekStatus:string|null;omzet:number;doelPercentage:number;percentageOmzet:number|null;totaalUren:number;totaalKosten:number;gemiddeldUurloon:number;ontbrekendUurloon:number;dagen:Dag[];medewerkers:Medewerker[]}) {
 const [omzet,setOmzet]=useState(p.omzet ? String(p.omzet).replace(".",",") : ""); const [doel,setDoel]=useState(String(p.doelPercentage).replace(".",",")); const [busy,setBusy]=useState(false); const [melding,setMelding]=useState("");
 const navigeren=(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);window.location.href="/rapportages?vestiging="+encodeURIComponent(String(f.get("vestiging")||""))+"&jaar="+encodeURIComponent(String(f.get("jaar")||""))+"&week="+encodeURIComponent(String(f.get("week")||""));};
 const opslaan=async()=>{setBusy(true);setMelding("");try{const r=await fetch("/api/rapportages/loonkosten",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({vestigingId:p.vestigingId,jaar:p.jaar,weeknummer:p.weeknummer,omzet:Number(omzet.replace(",","."))||0,doelPercentage:Number(doel.replace(",","."))})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Opslaan mislukt.");window.location.reload();}catch(e){setMelding(e instanceof Error?e.message:"Opslaan mislukt.");}finally{setBusy(false);}};
 return <section className="space-y-6">
  <form onSubmit={navigeren} className="grid gap-3 rounded-2xl border bg-white p-5 shadow-sm sm:grid-cols-4">
   <label className="text-sm font-medium">Vestiging<select name="vestiging" defaultValue={p.vestigingId} className="mt-1 w-full rounded-xl border px-3 py-2">{p.vestigingen.map(v=><option key={v.id} value={v.id}>{v.naam}</option>)}</select></label>
   <label className="text-sm font-medium">Jaar<input name="jaar" type="number" defaultValue={p.jaar} className="mt-1 w-full rounded-xl border px-3 py-2"/></label>
   <label className="text-sm font-medium">Week<input name="week" type="number" min="1" max="53" defaultValue={p.weeknummer} className="mt-1 w-full rounded-xl border px-3 py-2"/></label>
   <button className="self-end rounded-xl bg-slate-900 px-4 py-2 font-semibold text-white">Week tonen</button>
  </form>
  <div className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-slate-400">Loonkosten planning</p><h2 className="mt-1 text-xl font-bold">Week {p.weeknummer} · {p.vestigingen.find(v=>v.id===p.vestigingId)?.naam||"Vestiging"}</h2><p className="mt-1 text-sm text-slate-500">{p.weekBestaat?"Status: "+p.weekStatus:"Deze planningweek bestaat nog niet."}</p></div><div className="flex flex-col gap-2 sm:flex-row"><label className="text-sm font-medium">Omzet week (€)<input value={omzet} onChange={e=>setOmzet(e.target.value)} inputMode="decimal" className="mt-1 w-40 rounded-xl border px-3 py-2"/></label><label className="text-sm font-medium">Doel loonkosten (%)<input value={doel} onChange={e=>setDoel(e.target.value)} inputMode="decimal" className="mt-1 w-32 rounded-xl border px-3 py-2"/></label><button onClick={opslaan} disabled={busy||!p.weekBestaat} className="self-end rounded-xl bg-slate-900 px-4 py-2 font-semibold text-white disabled:opacity-50">{busy?"Opslaan...":"Opslaan"}</button></div></div>{melding&&<p className="mt-3 text-sm text-slate-600">{melding}</p>}</div>
  <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{[["Geplande uren",p.totaalUren.toFixed(2)],["Geplande loonkosten",euro(p.totaalKosten)],["Gem. uurloon",euro(p.gemiddeldUurloon)],["Loonkosten % omzet",p.percentageOmzet==null?"—":p.percentageOmzet.toFixed(1).replace(".",",")+"%"],["Doel",p.doelPercentage.toFixed(1).replace(".",",")+"%"]].map(x=><div key={x[0]} className="rounded-2xl border bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">{x[0]}</p><p className="mt-2 text-2xl font-bold">{x[1]}</p></div>)}</div>
  {p.percentageOmzet!=null&&<div className={p.percentageOmzet<=p.doelPercentage?"rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800":"rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800"}>{p.percentageOmzet<=p.doelPercentage?"De geplande loonkosten liggen binnen het ingestelde doel van "+p.doelPercentage.toFixed(1).replace(".",",")+"%.":"De geplande loonkosten liggen boven het ingestelde doel van "+p.doelPercentage.toFixed(1).replace(".",",")+"%."}</div>}
  {p.ontbrekendUurloon>0&&<div className="rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-800">Bij {p.ontbrekendUurloon} geplande medewerkerbezetting(en) ontbreekt het uurloon. Deze uren zijn niet meegenomen in de loonkosten.</div>}
  <div className="rounded-2xl border bg-white shadow-sm"><div className="border-b p-5"><h2 className="font-bold">Per dag</h2><p className="mt-1 text-sm text-slate-500">Geplande uren en loonkosten op basis van de huidige planning.</p></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left text-slate-500"><th className="p-4">Dag</th><th className="p-4">Uren</th><th className="p-4">Loonkosten</th><th className="p-4">Gem. uurloon</th></tr></thead><tbody>{p.dagen.map(d=><tr key={d.datum} className="border-b last:border-0"><td className="p-4 font-semibold">{datum(d.datum)}</td><td className="p-4">{d.uren.toFixed(2)}</td><td className="p-4">{euro(d.kosten)}</td><td className="p-4">{d.uren>d.ontbrekendUurloon?euro(d.kosten/(d.uren-d.ontbrekendUurloon)):"—"}</td></tr>)}</tbody></table></div></div>
  <div className="rounded-2xl border bg-white shadow-sm"><div className="border-b p-5"><h2 className="font-bold">Mix per medewerker</h2><p className="mt-1 text-sm text-slate-500">Uren, uurloon en aandeel in de geplande loonkosten.</p></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left text-slate-500"><th className="p-4">Medewerker</th><th className="p-4">Uurloon</th><th className="p-4">Uren</th><th className="p-4">Loonkosten</th><th className="p-4">Mix</th></tr></thead><tbody>{p.medewerkers.map(m=><tr key={m.medewerkerId} className="border-b last:border-0"><td className="p-4 font-semibold">{m.naam}</td><td className="p-4">{m.uurloon==null?"Ontbreekt":euro(m.uurloon)}</td><td className="p-4">{m.uren.toFixed(2)}</td><td className="p-4">{euro(m.kosten)}</td><td className="p-4">{p.totaalKosten?((m.kosten/p.totaalKosten)*100).toFixed(1).replace(".",",")+"%":"—"}</td></tr>)}</tbody></table></div></div>
 </section>;
}
